package com.revenera.gcs.implementor;

import com.flexnet.external.type.*;
import com.flexnet.external.webservice.keygenerator.LicGeneratorException;
import com.revenera.gcs.utils.GeneratorImplementor;
import com.revenera.gcs.utils.Log;
import org.apache.commons.lang3.ArrayUtils;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;


@SuppressWarnings("unused")
@GeneratorImplementor(technology = "ACME")
public class AcmeLicenseGenerator extends AbstractImplementor {

  static Function<Stream<Object>, Object> text_concatenate = list ->
          list.map(Object::toString).collect(Collectors.joining("\n"));

  static Function<Stream<Object>, Object>  binary_concatenate = list ->
          list.reduce(new byte[]{}, (a,b) -> ArrayUtils.addAll((byte[])a, (byte[])b));


  @Override
  public String technologyName() {
    return "ACME License Technology";
  }

  @Override
  public String technologyId() {
    return "ACME";
  }

  @Override
  public GeneratorResponse generateLicense(final GeneratorRequest request) throws LicGeneratorException {
    logger.in();


    return new GeneratorResponse() {
      {
        /* TODO create a LicenseFileMapItem for each license file definition as set-up in FNO License Technology */
        this.licenseFiles = Arrays.asList(
                new LicenseFileMapItem() {
                  {
                    this.name = "License";
                    this.value = request.getEntitledProducts().stream()
                                        .map(x -> x.getName() + " | " + x.getVersion() + " | " + request.getFulfillCount())
                                        .collect(Collectors.joining("\n"));
                  }
                },
                new LicenseFileMapItem() {
                  {
                    this.name = "Data";
                    this.value = String.join("\n", request.getSoldTo().getName(), request.getEntitlementID(), request.getActivationID(), request.getFulfilementID());
                  }
                },
                new LicenseFileMapItem() {
                  {
                    this.name = "Binary";
                    this.value = "license text".getBytes();
                  }
                });

        this.complete = true;

        this.message = "generated by " + technologyName();

        logger.yaml(Log.Level.debug, this.licenseFiles);
      }
    };
  }

  @Override
  public ConsolidatedLicense consolidateFulfillments(final FulfillmentRecordSet request) throws LicGeneratorException {
    logger.in();


    final Map<String, Function<Stream<Object>, Object>> concatenatorMap =
            request.getFulfillments().get(0).getLicenseTechnology().getLicenseFileDefinitions()
                   .stream()
                   .collect(Collectors.toMap(LicenseFileDefinition::getName,
                                     x -> x.getLicenseStorageType() == LicenseFileTypeENC.TEXT ? text_concatenate : binary_concatenate));
    logger.yaml(Log.Level.debug, concatenatorMap);

    return new ConsolidatedLicense() {
      {
        this.fulfillments = request.getFulfillments();

        this.licenseText = null;

        this.licenseFileName = null;

        request.getFulfillments().stream().findAny().ifPresent(fid -> {
          this.licenseFileNames = fid.getLicenseFileNames();

          logger.yaml(Log.Level.debug, this.licenseFileNames);
        });

        /* TODO - pull out the license data for each license file definition and concatenate */


        this.licFiles = request.getFulfillments()
                               .stream()
                               .flatMap(x -> x.getLicenseFiles().stream())
                               .collect(Collectors.groupingBy(LicenseFileMapItem::getName))
                               .entrySet()
                               .stream()
                               .map(item -> new LicenseFileMapItem() {
          {
            this.name = item.getKey();

            this.value = concatenatorMap.get(this.name).apply(item.getValue().stream().map(LicenseFileMapItem::getValue));
          }
        }).collect(Collectors.toList());

        logger.yaml(Log.Level.debug, this.licFiles);

      }
    };
  }


}
