package com.revenera.gcs.implementor;

import com.flexnet.external.type.*;
import com.flexnet.external.webservice.keygenerator.LicGeneratorException;
import com.revenera.gcs.utils.GeneratorImplementor;
import com.revenera.gcs.utils.Log;
import com.revenera.gcs.utils.Utils;

import java.util.ArrayList;
import java.util.Collections;

@GeneratorImplementor(technology = "DEF")
public final class DefaultLicenseGenerator extends AbstractImplementor {
  private final static Log logger = Log.create(DefaultLicenseGenerator.class);

  @Override
  public String technologyId() {
    return ImplementorFactory.default_technology_id;
  }

  @Override
  public String technologyName() {
    return "Default License Technology";
  }

  @Override
  public Status validateProduct(final ProductRequest product) {
    logger.in();
    return new Status() {
      {
        this.message = Utils.safeSerializeYaml(product);
        this.code = 0;
      }
    };
  }

  @Override
  public Status validateLicenseModel(final LicenseModelRequest model) throws LicGeneratorException {
    logger.in();
    return new Status() {
      {
        this.message = Utils.safeSerializeYaml(model);
        this.code = 0;
      }
    };
  }

  @Override
  public GeneratorResponse generateLicense(GeneratorRequest request) throws LicGeneratorException {

    return new GeneratorResponse() {
      {
        this.licenseFiles = Collections.singletonList(new LicenseFileMapItem() {
          {
            this.name = "License";
            this.value = Utils.safeSerializeYaml(request); // YAML dump of request
          }
        });

        this.licenseText = "";

        this.message = "generated by " + technologyName();

        this.complete = true;
      }
    };
  }

  @Override
  public ConsolidatedLicense consolidateFulfillments(final FulfillmentRecordSet fulfillmentRecordset) throws LicGeneratorException {
    logger.in();
    return new ConsolidatedLicense() {
      {
        this.fulfillments = fulfillmentRecordset.getFulfillments();

        this.licenseFileName = "License";

        this.binaryLicense = null;

        this.criteria = "Hello world...";

        this.licenseFileNames = Collections.singletonList(new LicenseFileDefinitionMapItem() {
          {
            this.name = "License";
          }
        });

        this.licFiles = Collections.singletonList(new LicenseFileMapItem() {
          {
            this.name = "License";
            this.value = Utils.safeSerializeYaml(fulfillmentRecordset); // YAML dump of request
          }
        });
      }
    };
  }

  @Override
  public LicenseFileDefinitionMap generateLicenseFilenames(final GeneratorRequest fileRec) throws LicGeneratorException {
    logger.in();
    return new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    };
  }

  @Override
  public LicenseFileDefinitionMap generateConsolidatedLicenseFilenames(final ConsolidatedLicenseResquest clRec) throws LicGeneratorException {
    logger.in();
    return new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    };
  }

  @Override
  public String generateCustomHostIdentifier(final HostIdRequest hostIdReq) throws LicGeneratorException {
    logger.in();
    return Utils.safeSerializeYaml(hostIdReq);
  }
}

